version: '3'

tasks:
  gen_order-svc_proto_files:
    cmds:
      - echo "Generating gRPC protobuf files"
      - protoc --proto_path=proto	--go_out=pb	--go_opt=paths=source_relative --go-grpc_out=pb	--go-grpc_opt=paths=source_relative	--experimental_allow_proto3_optional	proto/*.proto 