version: '3'

# works on windows 
tasks: 
  gen_proto_files:
    cmds:
      - echo "Generating gRPC protobuf files" 
      - protoc --plugin=protoc-gen-ts_proto=".\\node_modules\\.bin\\protoc-gen-ts_proto.cmd" --ts_proto_out=./proto --ts_proto_opt=nestJS=true -I=./proto ./proto/*.proto # windows configuration
      # - protoc -I ./proto --plugin=protoc-gen-ts_proto=./node_modules/.bin/protoc-gen-ts_proto.cmd --ts_proto_out=./proto --ts_proto_opt=nestJS=true ./proto/*.proto # linux configuration